services:
  backend:
    image: ystnysn/florist-backend:latest
    ports:
      - "8081:8080"
    networks:
      - back-tier
    env_file:
      - ./config.env
    # environment:
    #   - GIN_MODE=release 
    #   - DB_HOST=${DB_HOST}
    #   - DB_PORT=${DB_PORT}
    #   - DB_USER=${DB_USER}
    #   - DB_PASS=${DB_PASS}
    #   - DB_NAME=${DB_NAME}
    volumes:
      - ./config.env:/src/.env
    command: ["./florist-gin"] 
    restart: always

  database:
    image: postgres:latest
    ports:
      - "5433:5432"
    networks:
      - back-tier
    command:
      - "/bin/sh" 
      - "-c"        
      - "cd /src && ls -a && cat .env"
    env_file:
      - ./config.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  # debug:
  #   image: busybox
  #   command: ["/bin/sh", "-c", "cd /src", "ls", "cat /src/.env"]
  #   volumes:
  #     - ./.env:/src/.env

volumes:
  pgdata:
    driver: local

configs:
  httpd-config:
    external: true

networks:
  back-tier: {}