name: CI/CD Pipeline
on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/florist-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Install sshpass
        run: sudo apt-get install -y sshpass
      
      - name: SSH into VPS
        run: |
          sudo sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.VPS_IPV4 }} "echo 'Logged in to VPS successfully'"
      
      - name: Debug
        run: |
          pwd
          ls
          cd /
          ls
          sudo docker images

      - name: Move into the repository and pull the lastest version
        run: |
          sudo docker pull ystnysn/florist-backend:latest
          cd /home/runner/work/florist-gin/florist-gin
          git checkout master
          git pull origin master
      
      - name: Docker compose
        run: |
          sudo docker-compose up

      

